# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40b11a9c972fd4e9d7030556ebd0f78bd0acb4490a5ad8a97bf59e8395aa85a7fbe3a3d3b0e892ec80476103210a5db639ee92bcefb8d018b26cf625f4a04ace

test:
  secret_key_base: 0a2485534fde7fdcaf4e5aea5dfaa202c57bb069c1630ae601edcc7b3ce83a23d1a0f927012844d4a6702b386931a3cff3a4998866c7341267aa057a81e32a39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
